baseURL = "https://tech-notizen-inno.github.io"
languageCode = "ru"
title = "Я.Практикум"
theme = "hugo-book"

ignoreFiles = [
    "^content/_templates/course-template.md",
    "course-template.md"
]

sectionPagesMenu = 'main'

[params]
  BookSection = '*'