[yandex-s3]
type = s3
provider = AWS
access_key_id = YCAJE9v7MojBe8Bpy4XCmyU1E 
secret_access_key = <>
region = ru-central1
endpoint = storage.yandexcloud.net

[minio]
type = s3
provider = Minio
env_auth = false
access_key_id = euR6pB9WHrukTjIPAZRn
secret_access_key = <>
region = ru-central1
endpoint = http://127.0.0.1:9000
